apiVersion: v1
kind: Service
metadata:
  name: bill-payment-service-v2
  labels:
    app: bill-payment-service-v2
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: bill-payment-service-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-payment-service-v2
  labels:
    app: bill-payment-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-payment-service-v2
  minReadySeconds: 240
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bill-payment-service-v2
    spec:
      containers:
      - name: bill-payment-service-v2
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/bill-payment-service:imgtag-v2
        envFrom:
        - configMapRef:
            name: common-services-config
        ports: 
        - name: http
          containerPort: 80 
        volumeMounts:
        - name: config-file
          mountPath: "/app/application-cfgprofile.yml"  # "secret-file" file will be created in "/app" directory
          subPath: application.yml
        - name: tz-lagos
          mountPath: /etc/localtime
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/description
                operator: In
                values:
                - all-apps
      volumes:
        - name: config-file
          secret:
            secretName: bill-payment-servicev2-config-file # name of the Secret
        - name: tz-lagos
          hostPath:
            path: /usr/share/zoneinfo/Africa/Lagos    
