apiVersion: v1
kind: Service
metadata:
  name: bill-payment-service
  labels:
    app: bill-payment-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: bill-payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-payment-service
  labels:
    app: bill-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-payment-service
  template:
    metadata:
      labels:
        app: bill-payment-service
    spec:
      containers:
      - name: bill-payment-service
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/bill-payment-service:imgtag
        resources:
          requests:
            memory: "200Mi"
        envFrom:
        - configMapRef:
            name: common-services-config
        ports: 
        - name: http
          containerPort: 80 
        volumeMounts:
        - name: config-file
          mountPath: "/app/application-cfgprofile.yml"  # "secret-file" file will be created in "/app" directory
          subPath: application.yml
        - name: tz-lagos
          mountPath: /etc/localtime
      nodeSelector:
        node.kubernetes.io/description: cfgprofile  
      volumes:
        - name: config-file
          secret:
            secretName: bill-payment-service-config-file # name of the Secret
        - name: tz-lagos
          hostPath:
            path: /usr/share/zoneinfo/Africa/Lagos    
